runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 2

env_variables:
  CLOUDSQL_CONNECTION_NAME: mysql:unix_socket='';dbname=''
  CLOUDSQL_USER: ''
  CLOUDSQL_PASSWORD: ''
